### ISSUE TITLE
What does the file ""train.txt"" look like?

### ISSUE THREAD

**Issue by WERush** [nassarofficial/SiameseNetworkCaffe#1]
Hi, i am confused about your input_source file ""train.txt"", what is the content of this file? In other project, the source file is looking like "/path/to/image1.jpg, label1". But what is this file looking like?

Thanks

**Comment by nassarofficial** [comment]
Hello, Check the readme, it is now updated with a sample of how the input source file looks like. If you use my files please let me know of your results or how successful it was :+1:
